# Generated by Django 3.2.16 on 2023-01-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='news',
            new_name='news_list',
        ),
    ]
