# Generated by Django 3.2.16 on 2023-01-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_rename_news_news_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_list',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
