# Generated by Django 3.2.16 on 2023-01-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='user',
            name='grade_letter',
            field=models.CharField(default='Г', max_length=5),
        ),
    ]
