# Generated by Django 3.2.16 on 2023-01-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('download_file', models.ImageField(upload_to='')),
                ('upload_file', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
