# Generated by Django 3.2.16 on 2023-01-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230128_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='upload_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
